/**
 * Nusuk Hajj Itinerary parser.
 *
 * The "My Hajj Itinerary" PDF generated by hajj.nusuk.sa is a fixed,
 * server-rendered template. The same labels, ordering, and date formats
 * appear for every pilgrim regardless of package. We can therefore parse
 * it deterministically with anchor-based regex, with no LLM cost or latency.
 *
 * If a field can't be located the parser leaves it empty rather than guessing,
 * and the caller can route the user to the manual Settings form to fill in.
 */

import { EMPTY_ITINERARY } from './sample-data';
import type { Itinerary } from './types';

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

const MONTH_MAP: Record<string, string> = {
  jan: '01', feb: '02', mar: '03', apr: '04', may: '05', jun: '06',
  jul: '07', aug: '08', sep: '09', oct: '10', nov: '11', dec: '12',
};

/** "20-May-2026" → "2026-05-20" */
function isoDate(input?: string): string {
  if (!input) return '';
  const m = input.match(/(\d{1,2})[-\s/](\w{3,9})[-\s/](\d{4})/);
  if (!m) return '';
  const day = m[1].padStart(2, '0');
  const month = MONTH_MAP[m[2].slice(0, 3).toLowerCase()];
  if (!month) return '';
  return `${m[3]}-${month}-${day}`;
}

/** "20-May" + year hint → "2026-05-20" */
function isoFromShort(short: string, fallbackYear: string): string {
  const m = short.match(/(\d{1,2})[-\s]+(\w{3})/i);
  if (!m) return '';
  const day = m[1].padStart(2, '0');
  const month = MONTH_MAP[m[2].slice(0, 3).toLowerCase()];
  if (!month) return '';
  return `${fallbackYear}-${month}-${day}`;
}

/** "01:25" → "1h 25m" */
function prettyDuration(hhmm?: string): string {
  if (!hhmm) return '';
  const m = hhmm.match(/(\d{1,2}):(\d{2})/);
  if (!m) return hhmm;
  const h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  return `${h}h ${String(min).padStart(2, '0')}m`;
}

/** Strip whitespace runs but keep word separation. */
function squash(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

/** Look at a window of text after an anchor and grab the first non-empty group. */
function grab(text: string, regex: RegExp, group = 1): string {
  const m = text.match(regex);
  return m && m[group] ? squash(m[group]) : '';
}

/**
 * Strip CJK / private-use Unicode icon glyphs that Nusuk PDFs use for icons.
 * These occupy the U+3B00–U+5C00 range and various other CJK blocks. They
 * render as garbled characters and can interfere with regex anchors.
 */
function stripIconGlyphs(text: string): string {
  // Remove characters in CJK Unified Ideographs and surrounding blocks
  // that Nusuk uses for icon fonts (U+3400–U+9FFF range covers them all)
  // Also remove lone surrogate-pair artifacts
  return text.replace(/[\u3400-\u9FFF\uE000-\uF8FF]/g, ' ');
}

/**
 * Day of Arafah lookup for known Hajj years (Saudi calendar).
 * Used to populate `itinerary.hajj.arafahDate` so the ritual timeline works.
 * Add new entries here each year — single source of truth.
 */
const ARAFAH_BY_YEAR: Record<string, string> = {
  '2026': '2026-05-27', // 9 Dhul-Hijjah 1447 AH
  '2027': '2027-05-16', // 9 Dhul-Hijjah 1448 AH (approx — verify nearer the time)
  '2028': '2028-05-05', // 9 Dhul-Hijjah 1449 AH (approx)
};

// --------------------------------------------------------------------------
// Format detection
// --------------------------------------------------------------------------

/** Returns true if the extracted text looks like a Nusuk itinerary PDF. */
export function isNusukItinerary(rawText: string): boolean {
  const t = rawText.toLowerCase();
  // Multiple anchors must hit so we don't false-positive on random PDFs
  let score = 0;
  const checks: Record<string, boolean> = {};

  // Primary anchors (exact phrases from the PDF)
  checks['my hajj itinerary'] = t.includes('my hajj itinerary');
  if (checks['my hajj itinerary']) score++;
  checks['first housing'] = t.includes('first housing');
  if (checks['first housing']) score++;
  checks['camp name'] = t.includes('camp name');
  if (checks['camp name']) score++;
  checks['flight linked successfully'] = t.includes('flight linked successfully');
  if (checks['flight linked successfully']) score++;
  checks['check in/out'] = t.includes('check in') && t.includes('check out');
  if (checks['check in/out']) score++;
  checks['visa status'] = /visa\s+(approved|pending|rejected)/i.test(rawText);
  if (checks['visa status']) score++;

  // Fallback anchors — broader patterns that appear in Nusuk PDFs
  // These help when CMap extraction is incomplete and only partial text is available
  if (score < 3) {
    checks['rawaf + nusuk patterns'] = /rawaf/i.test(rawText) && /pilgrim/i.test(rawText);
    if (checks['rawaf + nusuk patterns']) score++;
    checks['hajj itinerary'] = t.includes('hajj') && t.includes('itinerary');
    if (checks['hajj itinerary'] && !checks['my hajj itinerary']) score++;
    checks['arriving + return'] = /arriving/i.test(rawText) && /return/i.test(rawText);
    if (checks['arriving + return']) score++;
    checks['emirates/saudia'] = /emirates|saudia|qatar airways/i.test(rawText);
    if (checks['emirates/saudia']) score++;
    checks['makkah/medina'] = /makkah|mecca|medina|madina|madinah/i.test(rawText);
    if (checks['makkah/medina']) score++;
  }

  console.log(`[Nusuk Parser] isNusukItinerary score: ${score} (need 3)`, checks);
  return score >= 3;
}

// --------------------------------------------------------------------------
// Parser
// --------------------------------------------------------------------------

export interface ParseResult {
  itinerary: Itinerary;
  /** 0–1 confidence based on how many critical fields were located. */
  confidence: number;
  /** Field paths we couldn't fill — caller can prompt user to fill these. */
  missing: string[];
}

export function parseNusukText(rawText: string): ParseResult {
  // Strip icon glyphs first — they interfere with regex anchors
  const cleaned = stripIconGlyphs(rawText);

  // Normalise: collapse weird whitespace but keep newlines so anchors work
  const text = cleaned.replace(/[ \t]+/g, ' ').replace(/\n{2,}/g, '\n');
  const flat = text.replace(/\s+/g, ' '); // for anchors that span linebreaks

  console.log(`[Nusuk Parser] Flat text length: ${flat.length}`);

  const data: Itinerary = JSON.parse(JSON.stringify(EMPTY_ITINERARY));
  const missing: string[] = [];

  // ---- Package: "RAWAF 573 OSTURAT" ----
  const pkg = flat.match(/RAWAF\s+(\d{2,4})\s+([A-Z][A-Z]+)/);
  if (pkg) {
    data.pilgrim.packageNumber = pkg[1];
    data.pilgrim.packageName = pkg[2].charAt(0) + pkg[2].slice(1).toLowerCase();
  } else {
    missing.push('pilgrim.packageNumber');
  }

  // ---- Pilgrim type: "Pilgrim Type B2C" ----
  const pType = grab(flat, /Pilgrim Type\s+(B2[CB])/i);
  if (pType) data.pilgrim.pilgrimType = pType.toUpperCase();

  // ---- Camp Name: "Camp Name AlMuaisim Camp" ----
  const camp = grab(flat, /Camp Name\s+([A-Za-z][A-Za-z0-9 '-]+?Camp)/i);
  if (camp) data.camp.name = camp;
  else missing.push('camp.name');

  // ---- Transportation ("Package Transportation") ----
  if (/Package Transportation/i.test(flat)) data.transportation = 'Package Transportation';

  // The itinerary's identity row is used only to derive a short display name.
  // Nationality, visa status, and the full legal name are deliberately not retained.
  const identityRow = flat.match(
    /([A-Z][A-Z'\s]+[A-Z])\s+(United Kingdom|United States|[A-Z][a-z]+(?: [A-Z][a-z]+)?)\s+(Visa\s+\w+)/
  );
  if (identityRow) {
    const parts = squash(identityRow[1]).split(/\s+/);
    if (parts.length >= 2) {
      const titled = parts.map(
        (p) => p.charAt(0) + p.slice(1).toLowerCase()
      );
      data.pilgrim.name = `${titled[0]} ${titled[titled.length - 1]}`;
    }
  } else {
    missing.push('pilgrim.name');
  }

  // ---- Guide: in the "Guides" section, format is NAME / +PHONE / PILGRIM_NAME ----
  // We pull the phone first (most distinctive), then look back for the name.
  const phone = grab(flat, /(\+\d{10,15})/);
  if (phone) {
    data.guide.phone = phone;
    // Guide name appears immediately before the phone in the Guides block
    const before = flat.split(phone)[0];
    const guideName = before.match(/([A-Z][A-Z]+(?:\s+[A-Z][A-Z]+){1,3})\s*$/);
    if (guideName) {
      const titled = guideName[1]
        .split(/\s+/)
        .map((p) => p.charAt(0) + p.slice(1).toLowerCase())
        .join(' ');
      data.guide.name = titled;
    }
  } else {
    missing.push('guide.phone');
  }

  // ---- Outbound flight ----
  // "ARRIVING 21-MAY-2026  Emirates - EK 32  Flight linked successfully: 7441468"
  const outboundHeader = flat.match(
    /ARRIVING\s+(\d{1,2}-\w{3}-\d{4})\s+(\w[\w\s]+?)\s+-\s+([A-Z]{2}\s*\d{1,4})/i
  );
  if (outboundHeader) {
    data.flights.outbound.arrivalDate = isoDate(outboundHeader[1]);
    data.flights.outbound.airline = squash(outboundHeader[2]);
    data.flights.outbound.flightNumbers = [outboundHeader[3].replace(/\s+/g, '')];
  }
  const outRef = grab(
    flat,
    /ARRIVING[\s\S]{0,200}?Flight linked successfully:\s*(\d+)/i
  );
  if (outRef) data.flights.outbound.bookingRef = outRef;

  // Outbound legs: "London 20-May - 19:50 ... Dubai 21-May - 05:55 ..."
  // The date and time may be split across lines in the extracted text,
  // so after flattening they appear as "London 20-May - 19:50".
  const legPattern = /([A-Z][a-z]+)\s+(\d{1,2}-\w{3})\s*-\s*(\d{1,2}:\d{2})/g;
  const detailedLegs: { city: string; date: string; time: string }[] = [];
  let m: RegExpExecArray | null;
  while ((m = legPattern.exec(flat)) !== null) {
    detailedLegs.push({ city: m[1], date: m[2], time: m[3] });
  }

  console.log(`[Nusuk Parser] Found ${detailedLegs.length} flight legs`);

  // First half = outbound, second half = return. Determined by the index where
  // the city changes from the outbound destination to the return origin.
  let outLegs: typeof detailedLegs = [];
  let retLegs: typeof detailedLegs = [];
  const splitIdx = detailedLegs.findIndex((l) => /^(Madina|Medina|Madinah)$/i.test(l.city));
  if (splitIdx > 0) {
    outLegs = detailedLegs.slice(0, splitIdx);
    retLegs = detailedLegs.slice(splitIdx);
  } else if (detailedLegs.length >= 2 && detailedLegs.length % 2 === 0) {
    const half = detailedLegs.length / 2;
    outLegs = detailedLegs.slice(0, half);
    retLegs = detailedLegs.slice(half);
  } else {
    outLegs = detailedLegs;
  }

  if (outLegs.length >= 2) {
    const yearGuess =
      (data.flights.outbound.arrivalDate || '').slice(0, 4) ||
      String(new Date().getFullYear());
    const first = outLegs[0];
    const last = outLegs[outLegs.length - 1];
    data.flights.outbound.departureCity = first.city;
    data.flights.outbound.departureDate = isoFromShort(first.date, yearGuess);
    data.flights.outbound.departureTime = first.time;
    data.flights.outbound.arrivalCity = last.city;
    data.flights.outbound.arrivalDate = isoFromShort(last.date, yearGuess);
    data.flights.outbound.arrivalTime = last.time;
    if (outLegs.length === 4) {
      data.flights.outbound.stopoverCity = outLegs[1].city;
    }
    // Pick up the second flight number from the outbound detail span.
    const firstIdx = flat.indexOf(`${first.city} ${first.date}`);
    const lastIdx = flat.indexOf(`${last.city} ${last.date}`, firstIdx);
    const span = firstIdx >= 0 && lastIdx > firstIdx
      ? flat.slice(firstIdx, lastIdx + 30)
      : flat;
    const allFlightCodes = span.match(/[A-Z]{2}\s*\d{1,4}/g) || [];
    const cleaned = allFlightCodes
      .map((c) => c.replace(/\s+/g, ''))
      .filter((c) => !/^EK0+$/.test(c));
    if (cleaned.length >= 2) data.flights.outbound.flightNumbers = cleaned.slice(0, 2);
  }
  // Layover duration: first "01:00" after "Wait time between flights"
  const outboundBlock = flat.split(/RETURN\s+\d/i)[0];
  const outLayover = grab(
    outboundBlock,
    /Wait time between flights[^\d]*(\d{1,2}:\d{2})/i
  );
  if (outLayover) data.flights.outbound.layoverDuration = prettyDuration(outLayover);

  // Arrival airport
  const outAirport = grab(
    outboundBlock,
    /Arrival Airport\s+([A-Za-z][A-Za-z .'-]+(?:Airport|International))/i
  );
  if (outAirport) data.flights.outbound.arrivalAirport = outAirport;

  // ---- Return flight ----
  const retHeader = flat.match(
    /RETURN\s+(\d{1,2}-\w{3}-\d{4})\s+(\w[\w\s]+?)\s+-\s+([A-Z]{2}\s*\d{1,4})/i
  );
  if (retHeader) {
    data.flights.return.departureDate = isoDate(retHeader[1]);
    data.flights.return.airline = squash(retHeader[2]);
    data.flights.return.flightNumbers = [retHeader[3].replace(/\s+/g, '')];
  }
  const retRef = grab(
    flat,
    /RETURN[\s\S]{0,200}?Flight linked successfully:\s*(\d+)/i
  );
  if (retRef) data.flights.return.bookingRef = retRef;

  const returnBlock = flat.split(/RETURN\s+\d/i)[1] || '';

  if (retLegs.length >= 2) {
    const yearGuess =
      (data.flights.return.departureDate || '').slice(0, 4) ||
      String(new Date().getFullYear());
    const first = retLegs[0];
    const last = retLegs[retLegs.length - 1];
    data.flights.return.departureCity = first.city;
    data.flights.return.departureDate = isoFromShort(first.date, yearGuess);
    data.flights.return.departureTime = first.time;
    data.flights.return.arrivalCity = last.city;
    data.flights.return.arrivalDate = isoFromShort(last.date, yearGuess);
    data.flights.return.arrivalTime = last.time;
    if (retLegs.length === 4) data.flights.return.stopoverCity = retLegs[1].city;
    const firstIdx = flat.indexOf(`${first.city} ${first.date}`);
    const lastIdx = flat.indexOf(`${last.city} ${last.date}`, firstIdx);
    const span = firstIdx >= 0 && lastIdx > firstIdx
      ? flat.slice(firstIdx, lastIdx + 30)
      : returnBlock;
    const allRetCodes = span.match(/[A-Z]{2}\s*\d{1,4}/g) || [];
    const retCleaned = allRetCodes
      .map((c) => c.replace(/\s+/g, ''))
      .filter((c) => !/^EK0+$/.test(c));
    if (retCleaned.length >= 2) data.flights.return.flightNumbers = retCleaned.slice(0, 2);
  }
  const retLayover = grab(
    returnBlock,
    /Wait time between flights[^\d]*(\d{1,2}:\d{2})/i
  );
  if (retLayover) data.flights.return.layoverDuration = prettyDuration(retLayover);

  const retAirport = grab(
    returnBlock,
    /Departure Airport\s+([A-Za-z][A-Za-z .'-]+(?:Airport|International))/i
  );
  if (retAirport) data.flights.return.departureAirport = retAirport;

  // ---- Hotels ----
  // Each hotel block has: NAME, City, "Check in DD-MMM-YYYY", "Check out DD-MMM-YYYY"
  // Limit the hotel name capture to 60 chars max to avoid over-matching unrelated text
  const hotelRegex =
    /([A-Z][A-Za-z'][A-Za-z .'-]{1,55}?(?:Hotel|Inn|Tower|Towers|Suites|Plaza|Palace|Resort|Rawafed))\s+(Makkah|Mecca|Medina|Madina|Madinah)\s+Check in\s+(\d{1,2}-\w{3}-\d{4})\s+Check out\s+(\d{1,2}-\w{3}-\d{4})/gi;
  const hotelMatches: RegExpExecArray[] = [];
  let h: RegExpExecArray | null;
  while ((h = hotelRegex.exec(flat)) !== null) hotelMatches.push(h);

  console.log(`[Nusuk Parser] Found ${hotelMatches.length} hotels`);

  for (const match of hotelMatches) {
    const hotel = {
      name: squash(match[1]),
      city: squash(match[2]),
      checkIn: isoDate(match[3]),
      checkOut: isoDate(match[4]),
    };
    const cityLower = hotel.city.toLowerCase();
    if (cityLower.startsWith('mak') || cityLower.startsWith('mec')) {
      data.hotels.hotel1 = hotel;
    } else if (cityLower.startsWith('mad') || cityLower.startsWith('med')) {
      data.hotels.hotel2 = hotel;
    }
  }
  if (!data.hotels.hotel1.name) missing.push('hotels.hotel1.name');
  if (!data.hotels.hotel2.name) missing.push('hotels.hotel2.name');

  // ---- Hajj dates: derive Arafah from outbound year ----
  const tripYear = (data.flights.outbound.departureDate || '').slice(0, 4);
  if (tripYear && ARAFAH_BY_YEAR[tripYear]) {
    data.hajj = { arafahDate: ARAFAH_BY_YEAR[tripYear] };
  }

  // ---- Confidence score ----
  const criticalFields: { ok: boolean }[] = [
    { ok: !!data.pilgrim.packageNumber },
    { ok: !!data.pilgrim.name },
    { ok: !!data.flights.outbound.flightNumbers.length },
    { ok: !!data.flights.outbound.departureDate },
    { ok: !!data.flights.return.flightNumbers.length },
    { ok: !!data.hotels.hotel1.name },
    { ok: !!data.hotels.hotel2.name },
    { ok: !!data.camp.name },
  ];
  const passed = criticalFields.filter((c) => c.ok).length;
  const confidence = passed / criticalFields.length;

  console.log(`[Nusuk Parser] Confidence: ${confidence} (${passed}/${criticalFields.length})`);
  console.log(`[Nusuk Parser] Missing: ${missing.join(', ') || 'none'}`);

  return { itinerary: data, confidence, missing };
}
