import type { Itinerary } from './types';

export const EMPTY_ITINERARY: Itinerary = {
  pilgrim: { name: '', packageName: '', packageNumber: '', pilgrimType: '' },
  guide: { name: '', phone: '' },
  camp: { name: '' },
  transportation: '',
  flights: {
    outbound: {
      airline: '',
      flightNumbers: [],
      departureCity: '',
      departureDate: '',
      departureTime: '',
      arrivalCity: '',
      arrivalDate: '',
      arrivalTime: '',
      arrivalAirport: '',
      stopoverCity: '',
      layoverDuration: '',
      bookingRef: '',
    },
    return: {
      airline: '',
      flightNumbers: [],
      departureCity: '',
      departureDate: '',
      departureTime: '',
      departureAirport: '',
      arrivalCity: '',
      arrivalDate: '',
      arrivalTime: '',
      stopoverCity: '',
      layoverDuration: '',
      bookingRef: '',
    },
  },
  hotels: {
    hotel1: { name: '', city: '', checkIn: '', checkOut: '' },
    hotel2: { name: '', city: '', checkIn: '', checkOut: '' },
  },
};

export const SAMPLE_ITINERARY: Itinerary = {
  pilgrim: {
    name: 'Abdikarim Ahmed',
    packageName: 'Osturat',
    packageNumber: '573',
    pilgrimType: 'B2C',
  },
  guide: {
    name: 'Mohammed Ahmed',
    phone: '+44 7904 993279',
  },
  camp: { name: 'AlMuaisim Camp' },
  transportation: 'Package Transportation',
  flights: {
    outbound: {
      airline: 'Emirates',
      flightNumbers: ['EK32', 'EK805'],
      departureCity: 'London (LHR)',
      departureDate: '2026-05-20',
      departureTime: '19:50',
      arrivalCity: 'Jeddah (JED)',
      arrivalDate: '2026-05-21',
      arrivalTime: '08:45',
      arrivalAirport: 'King Abdulaziz International Airport',
      stopoverCity: 'Dubai',
      layoverDuration: '1h 00m',
      bookingRef: '7441468',
    },
    return: {
      airline: 'Emirates',
      flightNumbers: ['EK808', 'EK29'],
      departureCity: 'Madina (MED)',
      departureDate: '2026-06-03',
      departureTime: '04:35',
      departureAirport: 'Prince Mohammad Bin Abdulaziz International Airport',
      arrivalCity: 'London (LHR)',
      arrivalDate: '2026-06-03',
      arrivalTime: '14:25',
      stopoverCity: 'Dubai',
      layoverDuration: '1h 25m',
      bookingRef: '7489392',
    },
  },
  hotels: {
    hotel1: {
      name: 'Osturat Emaar Hotel',
      city: 'Makkah',
      checkIn: '2026-05-20',
      checkOut: '2026-05-31',
    },
    hotel2: {
      name: 'Tulip Inn AlDar Rawafed',
      city: 'Madina',
      checkIn: '2026-05-31',
      checkOut: '2026-06-03',
    },
  },
};
